//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMSCloudbuilderPresentation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductId { get; set; }
        public int ProductBusinessUnitId { get; set; }
        public int ProductAuthorID { get; set; }
        public bool ProductoIsActive { get; set; }
        public System.DateTime ProductCreationDate { get; set; }
        public Nullable<System.DateTime> ProductArchiveDate { get; set; }
        public int ProductShowId { get; set; }
        public Nullable<int> ProductCategory1 { get; set; }
        public string ProductCategory2 { get; set; }
        public string ProductMainTitle { get; set; }
        public string ProductSubTitle { get; set; }
        public string ProductImageFile { get; set; }
        public string ProductVideoFile { get; set; }
        public string ProductScreenVideoFile {get; set;}
        public string ProductDatasheetFile { get; set; }
        public string ProductpocEmail { get; set; }
        public string ProductpocAbout { get; set; }
        public string ProductLeftBullet1 { get; set; }
        public string ProductLeftBullet2 { get; set; }
        public string ProductLeftBullet3 { get; set; }
        public string ProductLeftBullet4 { get; set; }
        public string ProductLeftBullet5 { get; set; }
        public string ProductRightBullet1 { get; set; }
        public string ProductRightBullet2 { get; set; }
        public string ProductRightBullet3 { get; set; }
        public string ProductRightBullet4 { get; set; }
        public string ProductRightBullet5 { get; set; }
        public string ProductRnSBullet1 { get; set; }
        public Nullable<System.DateTime> ProductDateTime { get; set; }
        public string ProductPocName { get; set; }
        public string ProductRnSBulletTitle { get; set; }
        public Nullable<int> ArchiveLevel { get; set; }
    }
}
